### ISSUE TITLE
Anatomogram: treatment of unplaced cell types 

### ISSUE THREAD

**Issue by pinin4fjords** [ebi-gene-expression-group/atlas-web-single-cell#141]
See e.g. https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-HCAD-10/results/anatomogram.

Many of the cell types visible in the first view at this link do not seem to be associated with any clickable region of the anatomogram. In fact if you 'click out' to the top level and back again, they all seem to disappear (as per https://github.com/ebi-gene-expression-group/atlas-web-single-cell/issues/136). 

Is it worth showing cell types in the heatmap with no relation to the anatomogram?

**Comment by alfonsomunozpomer** [comment]
This experiment was in the [list that Silvie compiled that had some issues either in the annotations or in the relationships between ontology data](https://github.com/ebi-gene-expression-group/atlas-web-single-cell/issues/127). So I’m closing this issue since it’s covered elsewhere.

> Is it worth showing cell types in the heatmap with no relation to the anatomogram?
In this regard, we agreed in earlier meetings that we would in fact do it because it won’t be uncommon, either because the anatomograms haven’t reached a certain level of detail or because new potential cell types haven’t been added to the ontologies yet.
