### ISSUE TITLE
HCA experiments wrongly linking to ENA

### ISSUE THREAD

**Issue by anjaf** [ebi-gene-expression-group/atlas-web-single-cell#145]
Example page: https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-HCAD-9/supplementary-information

Issue:
Under the Resources header, we show a non-working link to ENA. The link in picking up the UUID of the HCA study as if it was an ENA study accession and tries to find it in ENA. 

The expected behaviour is the following:
In case of HCA studies, we will have a HCA study accessions in the `Comment[SecondaryAccession]` field in the IDF. 
This accession is a UUID which can be used to look up the study in the HCA data portal. 
The target link for the example above should be https://data.humancellatlas.org/explore/projects/4d6f6c96-2a83-43d8-8fe1-0f53bffd4674

**Comment by alfonsomunozpomer** [comment]
https://www.pivotaltracker.com/story/show/176997080

**Comment by pcm32** [comment]
This is still occurring on wwwdev, we need to check if a PR was merged for this or not.

**Comment by pcm32** [comment]
My understanding is that now this is only failing due to return characters in the IDFs, correct? So no longer a software issue. Any working example that you could point us to @alfonsomunozpomer to corroborate that this is working software side to close this? Thanks.

**Comment by alfonsomunozpomer** [comment]
If you go to the experiment mentioned by Anja you won’t see an invalid link to ENA using the HCA ID, which fixes the issue. Other experiments with valid links to ENA, ArrayExpress or EGA will show the links. It’s worth noting that at the moment we’re not linking to HCA.

Links to GEO won’t be displayed because, for some reason, links outside `.eb.ac.uk` are not reachable and time out. Probably a proxy issue, but it’s a different issue.

**Comment by pcm32** [comment]
Ok, since this is no longer a software issue, lets close this and I'll add a new issue to keep in mind that we need to ask about the external access from tomcat machines.
