### ISSUE TITLE
Issue: labels cut off in anatomogram heatmap

### ISSUE THREAD

**Issue by ngeorgeebi** [ebi-gene-expression-group/atlas-web-single-cell#266]
https://www.ebi.ac.uk/gxa/sc/experiments/E-HCAD-9/results/anatomogram

If you look at the heatmap here you can see that the labels on the right side of the heatmap are cut off/shortened. This is the case even if you zoom out in the page

**Comment by alfonsomunozpomer** [comment]
We need to fix: 
1. The labels are missing the first word (it should be there)
2. The second to last words in the labels are showing only the first character followed by an ellipsis (we want at least one word, even if that means making the heatmap a bit narrower) *
3. The tooltip text is showing all the words without spaces, but they should be preserved

<span>*</span> This one’s going to be tricky because it’s up to Highcharts, but we can try to force it to behave as we want

There’s a fucntion that breaks a cell type “phrase” to words split by `<br>` and probably Highcharts is sanitisin the text before showin the tooltips/labels.

**Comment by lingyun1010** [comment]
Resolved by updating js bundle.
