### ISSUE TITLE
In case of Anndata Supplementary Information tab needs a different content

### ISSUE THREAD

**Issue by ke4** [ebi-gene-expression-group/atlas-web-single-cell#395]
In case of Anndata Supplementary information tab needs a different content in the `Analysis Methods` section.
@sfexova is going to add the proper requirements to this ticket.

**Comment by sfexova** [comment]
Hi @ke4 so I checked with @pmb59 and turns out I was wrong and misled you - there should be values in the Analysis Methods table under the Supplementary tab for AnnData experiments - the dataprods get it from the paper/authors and manually insert into a yaml file for loading. So the table should not be empty even for experiments we haven't reanalysed ourselves.
I'm wondering whether we should nevertheless highlight the fact by adding a note (could be just a footnote underneath the table) "This analysis summary is based on information provided by the authors or described in the linked publication" or something along those lines. Or do you think that's an overkill?

**Comment by sfexova** [comment]
re the wording for the note we discussed (that will go under the Analysis methods header and above the table) - happy with this @pmb59 @anilthanki? 
"This analysis summary is based on information provided by the authors or described in the associated publication"

**Comment by anilthanki** [comment]
May be we need something to clarify that these data is not reanalysed by us..

**Comment by sfexova** [comment]
that info will be included in the tooltip that appears when ppl hover over the icon but probably good to mention it here too - sth like this then?
"This methods summary is based on information provided by the authors or described in the associated publication, the data have not been re-analysed by Single Cell Expression Atlas"
